# Generated by Django 4.1.2 on 2023-06-27 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_producto_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marca',
            old_name='nombbre',
            new_name='nombre',
        ),
    ]
