# Generated by Django 4.0.5 on 2024-12-03 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lukaspet_app', '0004_transaccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaccion',
            name='id_transaccion',
        ),
        migrations.AddField(
            model_name='transaccion',
            name='codigo_autorizacion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
