# Generated by Django 4.0.5 on 2024-12-03 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lukaspet_app', '0005_remove_transaccion_id_transaccion_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaccion',
        ),
    ]
