# Generated by Django 4.2.17 on 2024-12-06 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lukaspet_app", "0008_pedido_delete_transaccion"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="comuna",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="pedido",
            name="direccion",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
